### ISSUE TITLE
pyOCD Usage: [Errno 110] Operation timed out

### ISSUE THREAD

**Issue by joerg65** [makerdiary/pitaya-link#3]
I get this error when  I try to flash an Ebyte E73-2G4M08S1C module. I have updated the firmware already to the newest version.
The host PC is Linux Mint 18.04.1.
There is only the small green led on. Other LED is not flickering during flash command.

This log I get with the error:

``pyocd flash  -t nrf52840 /home/joerg/Development/nrf5/nRF5_SDK_17.0.0_9d13099/examples/proprietary_rf/esb_low_power_ptx/pca10056/blank/armgcc/_build/nrf52840_xxaa.hex
0001493:CRITICAL:__main__:uncaught exception: [Errno 110] Operation timed out
Traceback (most recent call last):
  File "/home/joerg/.local/lib/python3.6/site-packages/pyocd/__main__.py", line 362, in run
    self._COMMANDS[self._args.cmd](self)
  File "/home/joerg/.local/lib/python3.6/site-packages/pyocd/__main__.py", line 520, in do_flash
    with session:
  File "/home/joerg/.local/lib/python3.6/site-packages/pyocd/core/session.py", line 302, in __enter__
    self.open()
  File "/home/joerg/.local/lib/python3.6/site-packages/pyocd/core/session.py", line 416, in open
    self._probe.open()
  File "/home/joerg/.local/lib/python3.6/site-packages/pyocd/probe/cmsis_dap_probe.py", line 147, in open
    self._link.open()
  File "/home/joerg/.local/lib/python3.6/site-packages/pyocd/utility/concurrency.py", line 28, in _locking
    return func(self, *args, **kwargs)
  File "/home/joerg/.local/lib/python3.6/site-packages/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 592, in open
    self._packet_count = self._protocol.dap_info(self.ID.MAX_PACKET_COUNT)
  File "/home/joerg/.local/lib/python3.6/site-packages/pyocd/probe/pydapaccess/cmsis_dap_core.py", line 133, in dap_info
    self.interface.write(cmd)
  File "/home/joerg/.local/lib/python3.6/site-packages/pyocd/probe/pydapaccess/interface/pyusb_backend.py", line 183, in write
    self.ep_out.write(data)
  File "/home/joerg/.local/lib/python3.6/site-packages/usb/core.py", line 406, in write
    return self.device.write(self, data, timeout)
  File "/home/joerg/.local/lib/python3.6/site-packages/usb/core.py", line 982, in write
    self.__get_timeout(timeout)
  File "/home/joerg/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 860, in intr_write
    timeout)
  File "/home/joerg/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 938, in __write
    _check(retval)
  File "/home/joerg/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out
``

**Comment by joerg65** [comment]
I found somewhere else that connected to USB3 port should work. And yes, changed from USB2 to USB3 port solved it.
